### ISSUE TITLE
Module modernization checklist

### ISSUE THREAD

**Issue by bergie** [noflo/noflo#410]
This is a meta-issue for tracking common tasks to bring the various `noflo-*` component libraries to up modern era. [noflo-docco](https://github.com/noflo/noflo-docco) is used as a testing ground for these.

Once we're happy with this list, it is a good idea to copy it as an issue for an individual module repo to track progress.
- [ ] Update all dependencies (there is probably a set of [greenkeeper](https://greenkeeper.io/) PRs for this)
- [ ] Update `package.json` license information
- [ ] Ensure `package.json` contains the [noflo keyword](https://www.npmjs.com/browse/keyword/noflo)
- [ ] Switch from cafeMocha to grunt-mocha-test
- [ ] Ensure grunt-mocha-phantomjs has [failWithOutput](https://github.com/jdcataldo/grunt-mocha-phantomjs#failwithoutput) set to true
- [ ] Set Travis to use Node.js 4.2
- [ ] Set up [Travis autodeploy](https://docs.travis-ci.com/user/deployment/npm/) to NPM
- [ ] Remove IRC notification from Travis config if set
- [ ] Ensure components have descriptions, icons, and that their ports have datatypes (description on ports are an extra bonus)
- [ ] Ensure components that can have errors have an appropriate `error` port and send to it
- [ ] Update components to the new Process API
- [ ] Port tests to [fbp-spec](https://github.com/flowbased/fbp-spec), or at least make them load components/graphs using ComponentLoader
- [ ] Annotate platform-specific components with `# @runtime noflo-nodejs` or `# @runtime noflo-browser` (`# @name Component` should be set only when component file name is different than class name e.g. `Resize-node.coffee` requests `# @name Resize`)
- [ ] Make sure components send only valid substreams with brackets. IP object metadata can be used for metadata purposes if needed
- [ ] Remove all uses of deprecated NoFlo apis, like `LoggingComponent` or `AsyncComponent`
- [ ] Add [grunt-noflo-lint](https://github.com/noflo/grunt-noflo-lint) or [noflo-lint](https://github.com/noflo/noflo-lint) to build config
- [ ] If components are stateful, make sure all state is cleared at `shutdown()`

[noflo-ipfs](https://github.com/noflo/noflo-ipfs/tree/master/spec) is a good example of using fbp-spec.

**Comment by automata** [comment]
@bergie maybe we can start referring to this issue on modernization PRs we're currently working, like :point_up:? Would be also nice to have a checklist with all libs so we can track which one was modernized and which not.

**Comment by bergie** [comment]
@automata yes, good idea!

**Comment by bergie** [comment]
It should be noted that porting components to Process API is pretty important, as this will ensure more consistent behavior (especially for pre-WirePattern components). It will also open the door for #373

**Comment by automata** [comment]
A list of component libraries from NoFlo org, it would be interesting to check out those ones we already _modernized_:

- [ ] [noflo/noflo-yaml](https://github.com/noflo/noflo-yaml)
- [ ] [noflo/noflo-mq](https://github.com/noflo/noflo-mq)
- [ ] [noflo/noflo-basecamp](https://github.com/noflo/noflo-basecamp)
- [ ] [noflo/noflo-xml](https://github.com/noflo/noflo-xml)
- [ ] [noflo/noflo-webserver](https://github.com/noflo/noflo-webserver)
- [ ] [noflo/noflo-html](https://github.com/noflo/noflo-html)
- [ ] [noflo/noflo-couchdb](https://github.com/noflo/noflo-couchdb)
- [ ] [noflo/noflo-restfulmetrics](https://github.com/noflo/noflo-restfulmetrics)
- [ ] [noflo/noflo-liquid](https://github.com/noflo/noflo-liquid)
- [ ] [noflo/noflo-markdown](https://github.com/noflo/noflo-markdown)
- [ ] [noflo/noflo-diffbot](https://github.com/noflo/noflo-diffbot)
- [ ] [noflo/noflo-filesystem](https://github.com/noflo/noflo-filesystem)
- [ ] [noflo/noflo-github](https://github.com/noflo/noflo-github)
- [ ] [noflo/noflo-git](https://github.com/noflo/noflo-git)
- [ ] [noflo/noflo-oembed](https://github.com/noflo/noflo-oembed)
- [ ] [noflo/noflo-redis](https://github.com/noflo/noflo-redis)
- [ ] [noflo/noflo-graphviz](https://github.com/noflo/noflo-graphviz)
- [ ] [noflo/noflo-ducksboard](https://github.com/noflo/noflo-ducksboard)
- [ ] [noflo/noflo-routers](https://github.com/noflo/noflo-routers)
- [ ] [noflo/noflo-groups](https://github.com/noflo/noflo-groups)
- [ ] [noflo/noflo-strings](https://github.com/noflo/noflo-strings)
- [ ] [noflo/noflo-objects](https://github.com/noflo/noflo-objects)
- [ ] [noflo/noflo-flow](https://github.com/noflo/noflo-flow)
- [ ] [noflo/noflo-packets](https://github.com/noflo/noflo-packets)
- [ ] [noflo/noflo-adapters](https://github.com/noflo/noflo-adapters)
- [ ] [noflo/noflo-dom](https://github.com/noflo/noflo-dom)
- [ ] [noflo/noflo-math](https://github.com/noflo/noflo-math)
- [ ] [noflo/noflo-docco](https://github.com/noflo/noflo-docco)
- [ ] [noflo/noflo-core](https://github.com/noflo/noflo-core)
- [ ] [noflo/noflo-physics](https://github.com/noflo/noflo-physics)
- [ ] [noflo/noflo-gravatar](https://github.com/noflo/noflo-gravatar)
- [ ] [noflo/noflo-css](https://github.com/noflo/noflo-css)
- [ ] [noflo/noflo-interaction](https://github.com/noflo/noflo-interaction)
- [ ] [noflo/noflo-ardrone](https://github.com/noflo/noflo-ardrone)
- [ ] [noflo/noflo-localstorage](https://github.com/noflo/noflo-localstorage)
- [ ] [noflo/noflo-websocket](https://github.com/noflo/noflo-websocket)
- [ ] [noflo/noflo-ajax](https://github.com/noflo/noflo-ajax)
- [ ] [noflo/noflo-gestures](https://github.com/noflo/noflo-gestures)
- [ ] [noflo/noflo-polymer](https://github.com/noflo/noflo-polymer)
- [ ] [noflo/noflo-indexeddb](https://github.com/noflo/noflo-indexeddb)
- [ ] [noflo/noflo-knex](https://github.com/noflo/noflo-knex)
- [ ] [noflo/noflo-blockchain](https://github.com/noflo/noflo-blockchain)
- [ ] [noflo/noflo-mandrill](https://github.com/noflo/noflo-mandrill)
- [ ] [noflo/noflo-graph](https://github.com/noflo/noflo-graph)
- [ ] [noflo/noflo-runtime](https://github.com/noflo/noflo-runtime)
- [ ] [noflo/noflo-finitedomain](https://github.com/noflo/noflo-finitedomain)
- [ ] [noflo/noflo-image](https://github.com/noflo/noflo-image)
- [ ] [noflo/noflo-embedly](https://github.com/noflo/noflo-embedly)
- [ ] [noflo/noflo-tween](https://github.com/noflo/noflo-tween)
- [ ] [noflo/noflo-facebook](https://github.com/noflo/noflo-facebook)
- [ ] [noflo/noflo-canvas](https://github.com/noflo/noflo-canvas)
- [ ] [noflo/noflo-gnome](https://github.com/noflo/noflo-gnome)
- [ ] [noflo/noflo-video](https://github.com/noflo/noflo-video)
- [ ] [noflo/noflo-ccv](https://github.com/noflo/noflo-ccv)
- [ ] [noflo/noflo-amd](https://github.com/noflo/noflo-amd)
- [ ] [noflo/noflo-react](https://github.com/noflo/noflo-react)
- [ ] [noflo/noflo-amqp](https://github.com/noflo/noflo-amqp)
- [ ] [noflo/noflo-xpress](https://github.com/noflo/noflo-xpress)
- [ ] [noflo/noflo-thegrid](https://github.com/noflo/noflo-thegrid)
- [ ] [noflo/noflo-google](https://github.com/noflo/noflo-google)
- [ ] [noflo/noflo-peer](https://github.com/noflo/noflo-peer)
- [ ] [noflo/noflo-tika](https://github.com/noflo/noflo-tika)
- [ ] [noflo/noflo-s3](https://github.com/noflo/noflo-s3)
- [ ] [noflo/noflo-browser-app](https://github.com/noflo/noflo-browser-app)
- [ ] [noflo/noflo-mirobot](https://github.com/noflo/noflo-mirobot)
- [ ] [noflo/noflo-browserfile](https://github.com/noflo/noflo-browserfile)
- [ ] [noflo/noflo-color](https://github.com/noflo/noflo-color)
- [ ] [noflo/noflo-webaudio](https://github.com/noflo/noflo-webaudio)
- [ ] [noflo/noflo-geometry](https://github.com/noflo/noflo-geometry)
- [ ] [noflo/noflo-mqtt](https://github.com/noflo/noflo-mqtt)
- [ ] [noflo/noflo-gpio](https://github.com/noflo/noflo-gpio)
- [ ] [noflo/noflo-imgflo](https://github.com/noflo/noflo-imgflo)
- [ ] [noflo/noflo-svg](https://github.com/noflo/noflo-svg)
- [ ] [noflo/noflo-stanbol](https://github.com/noflo/noflo-stanbol)
- [ ] [noflo/noflo-sharp](https://github.com/noflo/noflo-sharp)
- [ ] [noflo/noflo-exif](https://github.com/noflo/noflo-exif)
- [ ] [noflo/noflo-rss](https://github.com/noflo/noflo-rss)
- [ ] [noflo/noflo-hackrf](https://github.com/noflo/noflo-hackrf)
- [ ] [noflo/noflo-filetype](https://github.com/noflo/noflo-filetype)
- [ ] [noflo/noflo-ipfs](https://github.com/noflo/noflo-ipfs)
- [ ] [noflo/noflo-jsjob](https://github.com/noflo/noflo-jsjob)

**Comment by bergie** [comment]
Since switching to Process API often implies changes to group handling, we may want to resolve #419 before we do that porting all around.

And in any case, it is advisable to do the modernization in two rounds:

* First do the other modernization tasks and make a new release
* Then port to Process API and make a release with a major version bump

**Comment by bergie** [comment]
Modules should have reasonably relaxed version dependency on `noflo`. Recommended: `0.x >= 0.5`

**Comment by bergie** [comment]
This is pretty much done now. Next round is going to be Process API
